In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
data=pd. read_csv(r"E:\Projects\Python\Arsenal FC\Arsenal.csv")

In [10]:
data.head()

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Match_Week,Match_Day,Kickoff_Time,Home_Team,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report
0,ENG-Premier League,2526,2025-08-17 Manchester Utd-Arsenal,Arsenal,Ben White,4,ENG,RB,27-313,70,...,1,Sun,16:30,Manchester Utd,Arsenal,0–1,Old Trafford,73475,Simon Hooper,/en/matches/643d26fd/Manchester-United-Arsenal...
1,ENG-Premier League,2526,2025-08-17 Manchester Utd-Arsenal,Arsenal,Bukayo Saka,7,ENG,FW,23-346,90,...,1,Sun,16:30,Manchester Utd,Arsenal,0–1,Old Trafford,73475,Simon Hooper,/en/matches/643d26fd/Manchester-United-Arsenal...
2,ENG-Premier League,2526,2025-08-17 Manchester Utd-Arsenal,Arsenal,David Raya,1,ESP,GK,29-336,90,...,1,Sun,16:30,Manchester Utd,Arsenal,0–1,Old Trafford,73475,Simon Hooper,/en/matches/643d26fd/Manchester-United-Arsenal...
3,ENG-Premier League,2526,2025-08-17 Manchester Utd-Arsenal,Arsenal,Declan Rice,41,ENG,CM,26-215,82,...,1,Sun,16:30,Manchester Utd,Arsenal,0–1,Old Trafford,73475,Simon Hooper,/en/matches/643d26fd/Manchester-United-Arsenal...
4,ENG-Premier League,2526,2025-08-17 Manchester Utd-Arsenal,Arsenal,Gabriel Magalhães,6,BRA,CB,27-241,90,...,1,Sun,16:30,Manchester Utd,Arsenal,0–1,Old Trafford,73475,Simon Hooper,/en/matches/643d26fd/Manchester-United-Arsenal...

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 585 entries, 0 to 584
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   league              585 non-null    str
 1   season              585 non-null    int64
 2   game                585 non-null    str
 3   Team                585 non-null    str
 4   Player              585 non-null    str
 5   jersey_number       585 non-null    int64
 6   nation              585 non-null    str
 7   Position            585 non-null    str
 8   Age                 585 non-null    str
 9   Minutes             585 non-null    int64
 10  Goals               585 non-null    int64
 11  Assists             585 non-null    int64
 12  Penalty_Goals       585 non-null    int64
 13  Penalty_Attempts    585 non-null    int64
 14  Shots               585 non-null    int64
 15  Shots_On_Target     585 non-null    int64
 16  Yellow_Cards        585 non-null    int64
 17  Red_Cards           585 non-null    int64
 18  Fouls_Committed     585 non-null    int64
 19  Fouls_Drawn         585 non-null    int64
 20  Offsides            585 non-null    int64
 21  Crosses             585 non-null    int64
 22  Tackles_Won         585 non-null    int64
 23  Interceptions       585 non-null    int64
 24  Own_Goals           585 non-null    int64
 25  Penalties_Won       585 non-null    int64
 26  Penalties_Conceded  585 non-null    int64
 27  game_id             585 non-null    str
 28  Match_Date          585 non-null    str
 29  Match_Week          585 non-null    int64
 30  Match_Day           585 non-null    str
 31  Kickoff_Time        585 non-null    str
 32  Home_Team           585 non-null    str
 33  Away_Team           585 non-null    str
 34  Match_Score         585 non-null    str
 35  Venue               585 non-null    str
 36  Attendance          585 non-null    int64
 37  Referee             585 non-null    str
 38  Match_Report        585 non-null    str
dtypes: int64(22), str(17)
memory usage: 178.4 KB

In [17]:
data.select_dtypes(include="object").info()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16556\1675590768.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.select_dtypes(include="object").info()

<class 'pandas.DataFrame'>
RangeIndex: 585 entries, 0 to 584
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   league        585 non-null    str
 1   game          585 non-null    str
 2   Team          585 non-null    str
 3   Player        585 non-null    str
 4   nation        585 non-null    str
 5   Position      585 non-null    str
 6   Age           585 non-null    str
 7   game_id       585 non-null    str
 8   Match_Date    585 non-null    str
 9   Match_Day     585 non-null    str
 10  Kickoff_Time  585 non-null    str
 11  Home_Team     585 non-null    str
 12  Away_Team     585 non-null    str
 13  Match_Score   585 non-null    str
 14  Venue         585 non-null    str
 15  Referee       585 non-null    str
 16  Match_Report  585 non-null    str
dtypes: str(17)
memory usage: 77.8 KB

In [18]:
data.describe()

,season,jersey_number,Minutes,Goals,Assists,Penalty_Goals,Penalty_Attempts,Shots,Shots_On_Target,Yellow_Cards,...,Fouls_Drawn,Offsides,Crosses,Tackles_Won,Interceptions,Own_Goals,Penalties_Won,Penalties_Conceded,Match_Week,Attendance
count,585.0,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,...,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.0,585.0,585.000000,585.000000
mean,2526.0,16.770940,64.307692,0.114530,0.087179,0.006838,0.006838,0.943590,0.317949,0.087179,...,0.697436,0.104274,1.160684,0.567521,0.442735,0.001709,0.0,0.0,19.535043,50639.627350
std,0.0,13.926501,30.114752,0.373172,0.288340,0.082477,0.082477,1.255903,0.623267,0.282339,...,0.926629,0.366956,2.040219,0.896705,0.778930,0.041345,0.0,0.0,11.047960,15258.104294
min,2526.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.000000,11240.000000
25%,2526.0,6.000000,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,10.000000,39820.000000
50%,2526.0,12.000000,79.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,20.000000,60167.000000
75%,2526.0,23.000000,90.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.0,0.0,29.000000,60274.000000
max,2526.0,56.000000,90.000000,3.000000,2.000000,1.000000,1.000000,7.000000,4.000000,1.000000,...,5.000000,3.000000,14.000000,6.000000,4.000000,1.000000,0.0,0.0,38.000000,73475.000000

In [19]:
data.describe(include=["str"])

,league,game,Team,Player,nation,Position,Age,game_id,Match_Date,Match_Day,Kickoff_Time,Home_Team,Away_Team,Match_Score,Venue,Referee,Match_Report
count,585,585,585,585,585,585,585,585,585,585,585,585,585,585,585,585,585
unique,1,38,1,25,12,12,541,38,38,6,9,20,20,15,20,17,38
top,ENG-Premier League,2025-08-17 Manchester Utd-Arsenal,Arsenal,Martín Zubimendi,ENG,"FW,MF",29-336,643d26fd,8/17/2025,Sat,16:30,Arsenal,Arsenal,0–1,Emirates Stadium,Chris Kavanagh,/en/matches/643d26fd/Manchester-United-Arsenal...
freq,585,16,585,38,169,90,2,16,16,276,169,297,288,75,297,77,16

In [31]:
top_5_goal_scorer= (data.groupby("Player")["Goals"].sum().sort_values(ascending=False).head(5))
top_5_goal_scorer

Player
Viktor Gyökeres     14
Eberechi Eze         7
Bukayo Saka          7
Leandro Trossard     6
Martín Zubimendi     5
Name: Goals, dtype: int64

In [34]:
top_5_assist_provider= (data.groupby("Player")["Assists"].sum().sort_values(ascending=False).head(5))
top_5_assist_provider

Player
Martin Ødegaard     6
Leandro Trossard    6
Jurriën Timber      5
Declan Rice         5
Bukayo Saka         5
Name: Assists, dtype: int64

5. Player Position Analysis

Identify each player's position and analyze how many unique players belong to each position.

In [46]:
player_positions = (
    data[["Player", "Position"]]
    .drop_duplicates()
    .sort_values(by="Player")
)

player_positions

                 Player Position
0             Ben White       RB
274           Ben White       DF
1           Bukayo Saka       FW
79          Bukayo Saka       AM
63          Bukayo Saka    FW,MF
..                  ...      ...
13   Riccardo Calafiori       LB
198     Viktor Gyökeres    FW,MF
14      Viktor Gyökeres       FW
94       William Saliba       DF
15       William Saliba       CB

[65 rows x 2 columns]

6. Goal Contribution Analysis

Create a new column called Goal Contribution:
Goal Contribution = Goals + Assists

In [53]:
data["Goal Contribution"] = data["Goals"] + data["Assists"]
top_5_goal_contributors= data.groupby("Player")["Goal Contribution"].sum().sort_values(ascending=False).head(5)
top_5_goal_contributors

Player
Viktor Gyökeres     15
Leandro Trossard    12
Bukayo Saka         12
Eberechi Eze         9
Declan Rice          9
Name: Goal Contribution, dtype: int64

7. Most Used Players

Find the Top 10 players who played the highest total number of minutes.

In [58]:
most_used_players=data.groupby("Player")["Minutes"].sum().sort_values(ascending=False).head(10)
most_used_players

Player
David Raya           3330
Declan Rice          3094
Martín Zubimendi     2992
Gabriel Magalhães    2751
William Saliba       2614
Jurriën Timber       2454
Viktor Gyökeres      2224
Bukayo Saka          2222
Leandro Trossard     2000
Eberechi Eze         1812
Name: Minutes, dtype: int64

8. Shooting Performance Analysis
Calculate the total number of:
•	Shots 
•	Shots on Target 
•	Goals 
for each player and identify the best attacking players.

In [63]:
top_attacking_players = ( data.groupby("Player")[["Goals", "Shots_On_Target", "Shots"]] .sum() 
.sort_values(by=["Goals", "Shots_On_Target"], ascending=False) )
top_attacking_players

                    Goals  Shots_On_Target  Shots
Player
Viktor Gyökeres        14               22     55
Bukayo Saka             7               27     71
Eberechi Eze            7               18     57
Leandro Trossard        6               15     53
Martín Zubimendi        5                9     27
Declan Rice             4               13     40
Mikel Merino            4                8     22
Gabriel Jesus           3               12     19
Noni Madueke            3                9     25
Gabriel Magalhães       3                7     27
Jurriën Timber          3                7     25
Kai Havertz             2                4     18
Gabriel Martinelli      1               13     29
Martin Ødegaard         1                8     22
Riccardo Calafiori      1                8     32
Piero Hincapié          1                2      3
Max Dowman              1                1      6
William Saliba          1                1      5
Ben White               0                1      5
Christian Nørgaard      0                1      2
Cristhian Mosquera      0                0      1
David Raya              0                0      0
Ethan Nwaneri           0                0      6
Kepa Arrizabalaga       0                0      0
Myles Lewis-Skelly      0                0      2

9. Shooting Accuracy
Create a new metric:
Shooting Accuracy = (Shots on Target / Total Shots) × 100
Identify the players with the highest shooting accuracy, using a reasonable minimum number of shots.

In [75]:
data["shooting_accuracy"]=data["Shots_On_Target"]/data["Shots"]*100
shooting_accuracy=data.groupby("Player")["shooting_accuracy"].mean().sort_values(ascending=False).dropna()
shooting_accuracy

Player
Gabriel Jesus         68.750000
Piero Hincapié        66.666667
Gabriel Martinelli    57.500000
Christian Nørgaard    50.000000
Bukayo Saka           38.119048
Declan Rice           37.500000
Viktor Gyökeres       35.416667
Riccardo Calafiori    32.843137
Mikel Merino          32.051282
Noni Madueke          30.555556
Eberechi Eze          30.214286
Gabriel Magalhães     29.166667
Martin Ødegaard       28.333333
Martín Zubimendi      28.125000
Jurriën Timber        24.444444
Leandro Trossard      23.148148
Kai Havertz           20.555556
Ben White             20.000000
William Saliba        20.000000
Max Dowman            12.500000
Cristhian Mosquera     0.000000
Ethan Nwaneri          0.000000
Myles Lewis-Skelly     0.000000
Name: shooting_accuracy, dtype: float64

10. Goals per 90 Minutes
Calculate:
Goals per 90 Minutes = (Goals / Minutes Played) × 90
Identify the most efficient goal scorers.

In [77]:
data["goals_per_90_minutes"]=data["Goals"]/data["Minutes"]*90
goals_per_90_minutes=data.groupby("Player")["goals_per_90_minutes"].mean().sort_values(ascending=False).dropna()
goals_per_90_minutes

Player
Gabriel Jesus         0.974628
Max Dowman            0.882353
Viktor Gyökeres       0.628142
Mikel Merino          0.409681
Bukayo Saka           0.354218
Gabriel Martinelli    0.272727
Eberechi Eze          0.254177
Leandro Trossard      0.243349
Kai Havertz           0.187500
Noni Madueke          0.150073
Martín Zubimendi      0.131579
Jurriën Timber        0.128571
Declan Rice           0.115385
Gabriel Magalhães     0.099507
Riccardo Calafiori    0.048754
Martin Ødegaard       0.041667
Piero Hincapié        0.040000
William Saliba        0.032258
Ethan Nwaneri         0.000000
Cristhian Mosquera    0.000000
David Raya            0.000000
Ben White             0.000000
Christian Nørgaard    0.000000
Kepa Arrizabalaga     0.000000
Myles Lewis-Skelly    0.000000
Name: goals_per_90_minutes, dtype: float64

11. Defensive Performance
Create a new metric:
Defensive Contribution = Tackles Won + Interceptions
Find the Top 10 defensive players based on this metric.

In [80]:
data["Difencive_Contribution"]=data["Tackles_Won"]+data["Interceptions"]
Difencive_Contribution=data.groupby("Player")["Difencive_Contribution"].mean().sort_values(ascending=False).dropna()
Difencive_Contribution

Player
Piero Hincapié        2.080000
Martín Zubimendi      2.052632
Jurriën Timber        1.966667
Declan Rice           1.833333
Ben White             1.500000
Cristhian Mosquera    1.450000
Gabriel Magalhães     1.312500
Riccardo Calafiori    1.230769
William Saliba        1.225806
Bukayo Saka           1.129032
Mikel Merino          1.000000
Leandro Trossard      0.774194
Eberechi Eze          0.750000
Martin Ødegaard       0.666667
Noni Madueke          0.576923
Kai Havertz           0.500000
Max Dowman            0.500000
Myles Lewis-Skelly    0.500000
Christian Nørgaard    0.428571
Gabriel Martinelli    0.300000
Viktor Gyökeres       0.166667
Gabriel Jesus         0.142857
David Raya            0.054054
Ethan Nwaneri         0.000000
Kepa Arrizabalaga     0.000000
Name: Difencive_Contribution, dtype: float64

12. Discipline Analysis
Identify the players with the highest number of:
•	Yellow Cards 
•	Red Cards 
•	Fouls Committed

In [86]:
player_discipline = (
    data.groupby("Player")[["Yellow_Cards", "Red_Cards", "Fouls_Committed"]]
    .sum().sort_values(by="Yellow_Cards", ascending=False )
)
player_discipline

                    Yellow_Cards  Red_Cards  Fouls_Committed
Player
Jurriën Timber                 5          0               38
Viktor Gyökeres                5          0               35
Riccardo Calafiori             5          0               26
Gabriel Magalhães              4          0               21
Martín Zubimendi               4          0               33
Cristhian Mosquera             4          0               17
Gabriel Jesus                  3          0                9
Myles Lewis-Skelly             3          0               10
Declan Rice                    3          0               26
Gabriel Martinelli             3          0               10
Piero Hincapié                 2          0               18
William Saliba                 2          0               22
Leandro Trossard               2          0               13
Bukayo Saka                    2          0               33
Eberechi Eze                   1          0               14
Kai Havertz                    1          0                8
David Raya                     1          0                0
Mikel Merino                   1          0               22
Ethan Nwaneri                  0          0                2
Ben White                      0          0                5
Christian Nørgaard             0          0                3
Martin Ødegaard                0          0                9
Kepa Arrizabalaga              0          0                0
Noni Madueke                   0          0               15
Max Dowman                     0          0                2